### ISSUE TITLE
Election Timeline

### ISSUE THREAD

**Issue by Gjoll** [Gjoll/UWH-Items#1]
Create timeline for Elections. Timeline should include dates and actions to be performed by that date. This includes all required and desired communications related to the elections.

Create online calendar with reminder ability to keep items from being forgotten.

**Comment by Gjoll** [comment]
Will GoMembership work for getting membership info including e-mail?
http://www.gomembership.com/features/membership-management.aspx

**Comment by assavu** [comment]
Need a quick outline after we review the bylaws.

**Comment by assavu** [comment]
Main: 
Nominations accepted
Nominations closed
Voting open
Voting closed
Tally results
Share results
Onboard new members

**Comment by Gjoll** [comment]
Timeline should include dates that we need to have software proposals to USOA committee. USOA meeting in march.
Also contact other sports, including Rugby and get their buy-in.

**Comment by Gjoll** [comment]
Ecnlosed is excel spread sheet with 2018 dates as required from bylaws.
[Voting Time Dependencies.xlsx](https://github.com/Gjoll/UWH-Items/files/1756675/Voting.Time.Dependencies.xlsx)
