### ISSUE TITLE
Team registration page.

### ISSUE THREAD

**Issue by Gjoll** [Gjoll/UWH-Items#19]
Should say "Select the person who is the primary team contact", not select the person you  are registering.

**Comment by shaljain** [comment]
Changed contact labels to say Team Contact First name etc.
The phrase 'select the person you are registering' doesn't show up in user mode. That's an admin mode artifact.  Take a look at the new club request when not logged in

<img width="854" alt="usoa-newclubrequest" src="https://user-images.githubusercontent.com/37684624/45992371-072ae080-c04f-11e8-946f-4e3924914cc8.png">
