### ISSUE TITLE
Nomination Process

### ISSUE THREAD

**Issue by Gjoll** [Gjoll/UWH-Items#2]
Determine process for nominations and process by which that person gets their bio on the ballot and the process by which we will insure that no nomination gets lost

Use Google forms?

**Comment by assavu** [comment]
Google Form: https://docs.google.com/forms/d/e/1FAIpQLSd7zftfGrCprl2AkfPhFWTFiuxOpn18xvHqcEZ2I1qBIX3i5A/viewform?usp=sf_link

Google Answer Spreadsheet:
https://docs.google.com/spreadsheets/d/1IHeLZlGXYtT92MErfYHcPURbj8l7c5Fxtzg7mg-kbNE/edit?usp=sharing
