### ISSUE TITLE
Review USOA Voting by-laws

### ISSUE THREAD

**Issue by assavu** [Gjoll/UWH-Items#5]

**Comment by Gjoll** [comment]
Here are USOA bylaws and UWH Committee rules for review.

[USOA_UWH_rules Original.pdf](https://github.com/Gjoll/UWH-Items/files/1556091/USOA_UWH_rules.Original.pdf)
[USOA Bylaws2005.pdf](https://github.com/Gjoll/UWH-Items/files/1556092/USOA.Bylaws2005.pdf)

**Comment by Gjoll** [comment]
Here is excel spreadsheet that defines the dates for 2018
[Voting Time Dependencies.xlsx](https://github.com/Gjoll/UWH-Items/files/1756674/Voting.Time.Dependencies.xlsx)
